dataset:
  test:
    class: CoDesignDataset
    mmap_dir: ./datasets/LNR
    specify_index: ./datasets/LNR/test.txt
    backbone_only: false
    use_covariance_matrix: true

dataloader:
  num_workers: 4
  batch_size: 64

backbone_only: false
n_samples: 4

sample_opt:
  energy_func: default
  energy_lambda: 0.8
