dataset:
  train:
    - class: CoDesignDataset
      mmap_dir: ./datasets/train_valid
      specify_index: ./datasets/train_valid/train.txt
      backbone_only: false
      cluster: ./datasets/train_valid/train.cluster
      use_covariance_matrix: true
    - class: CoDesignDataset
      mmap_dir: ./datasets/ProtFrag
      backbone_only: false
      use_covariance_matrix: true
  valid:
    class: CoDesignDataset
    mmap_dir: ./datasets/train_valid
    specify_index: ./datasets/train_valid/valid.txt
    backbone_only: false
    use_covariance_matrix: true

dataloader:
  shuffle: true
  num_workers: 4
  wrapper:
    class: DynamicBatchWrapper
    complexity: n**2
    ubound_per_batch: 480000  # batch size ~140

trainer:
  class: IFTrainer
  config:
    max_epoch: 60
    save_topk: 10
    save_dir: ./ckpts/ifencoder
    patience: 10
    metric_min_better: true

    optimizer:
      class: AdamW
      lr: 1.0e-4
    
    scheduler:
      class: ReduceLROnPlateau
      factor: 0.8
      patience: 5
      mode: min
      frequency: val_epoch
      min_lr: 5.0e-6

model:
  class: IFEncoder
  ldm_ckpt: ""
  hidden_size: 128
  out_size: 32
  n_layers: 3
  n_rbf: 32
  cutoff: 20.0